apiVersion: api.cerbos.dev/v1
resourcePolicy:
    version: "default"
    resource: "service"
    importDerivedRoles:
        - common_roles
    rules:
        - actions: ["*"]
          effect: EFFECT_ALLOW
          roles:
              - admin
        - actions: ['read']
          effect: EFFECT_ALLOW
          roles:
              - user
