// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.1
// source: api/address-api/address-api.proto

package addressapi

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllAddressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *FindAllAddressRequest) Reset() {
	*x = FindAllAddressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_address_api_address_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllAddressRequest) ProtoMessage() {}

func (x *FindAllAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_address_api_address_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllAddressRequest.ProtoReflect.Descriptor instead.
func (*FindAllAddressRequest) Descriptor() ([]byte, []int) {
	return file_api_address_api_address_api_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllAddressRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type FindAllAddressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []string `protobuf:"bytes,1,rep,name=address,proto3" json:"address,omitempty"`
}

func (x *FindAllAddressResponse) Reset() {
	*x = FindAllAddressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_address_api_address_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllAddressResponse) ProtoMessage() {}

func (x *FindAllAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_address_api_address_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllAddressResponse.ProtoReflect.Descriptor instead.
func (*FindAllAddressResponse) Descriptor() ([]byte, []int) {
	return file_api_address_api_address_api_proto_rawDescGZIP(), []int{1}
}

func (x *FindAllAddressResponse) GetAddress() []string {
	if x != nil {
		return x.Address
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WardFullName     string `protobuf:"bytes,1,opt,name=ward_full_name,json=wardFullName,proto3" json:"ward_full_name,omitempty"`
	DistrictFullName string `protobuf:"bytes,2,opt,name=district_full_name,json=districtFullName,proto3" json:"district_full_name,omitempty"`
	ProvinceFullName string `protobuf:"bytes,3,opt,name=province_full_name,json=provinceFullName,proto3" json:"province_full_name,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_address_api_address_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_api_address_api_address_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_api_address_api_address_api_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetWardFullName() string {
	if x != nil {
		return x.WardFullName
	}
	return ""
}

func (x *Address) GetDistrictFullName() string {
	if x != nil {
		return x.DistrictFullName
	}
	return ""
}

func (x *Address) GetProvinceFullName() string {
	if x != nil {
		return x.ProvinceFullName
	}
	return ""
}

type CheckExistAddressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address *Address `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *CheckExistAddressRequest) Reset() {
	*x = CheckExistAddressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_address_api_address_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckExistAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExistAddressRequest) ProtoMessage() {}

func (x *CheckExistAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_address_api_address_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExistAddressRequest.ProtoReflect.Descriptor instead.
func (*CheckExistAddressRequest) Descriptor() ([]byte, []int) {
	return file_api_address_api_address_api_proto_rawDescGZIP(), []int{3}
}

func (x *CheckExistAddressRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type CheckExistAddressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address *Address `protobuf:"bytes,1,opt,name=address,proto3,oneof" json:"address,omitempty"`
}

func (x *CheckExistAddressResponse) Reset() {
	*x = CheckExistAddressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_address_api_address_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckExistAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExistAddressResponse) ProtoMessage() {}

func (x *CheckExistAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_address_api_address_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExistAddressResponse.ProtoReflect.Descriptor instead.
func (*CheckExistAddressResponse) Descriptor() ([]byte, []int) {
	return file_api_address_api_address_api_proto_rawDescGZIP(), []int{4}
}

func (x *CheckExistAddressResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type FindAllNameOfAddressUnitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string       `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Unit *AddressUnit `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
}

func (x *FindAllNameOfAddressUnitRequest) Reset() {
	*x = FindAllNameOfAddressUnitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_address_api_address_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllNameOfAddressUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllNameOfAddressUnitRequest) ProtoMessage() {}

func (x *FindAllNameOfAddressUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_address_api_address_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllNameOfAddressUnitRequest.ProtoReflect.Descriptor instead.
func (*FindAllNameOfAddressUnitRequest) Descriptor() ([]byte, []int) {
	return file_api_address_api_address_api_proto_rawDescGZIP(), []int{5}
}

func (x *FindAllNameOfAddressUnitRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FindAllNameOfAddressUnitRequest) GetUnit() *AddressUnit {
	if x != nil {
		return x.Unit
	}
	return nil
}

type AddressUnit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *AddressUnit) Reset() {
	*x = AddressUnit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_address_api_address_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressUnit) ProtoMessage() {}

func (x *AddressUnit) ProtoReflect() protoreflect.Message {
	mi := &file_api_address_api_address_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressUnit.ProtoReflect.Descriptor instead.
func (*AddressUnit) Descriptor() ([]byte, []int) {
	return file_api_address_api_address_api_proto_rawDescGZIP(), []int{6}
}

func (x *AddressUnit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddressUnit) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type FindAllNameOfAddressUnitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unit []*AddressUnit `protobuf:"bytes,1,rep,name=unit,proto3" json:"unit,omitempty"`
}

func (x *FindAllNameOfAddressUnitResponse) Reset() {
	*x = FindAllNameOfAddressUnitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_address_api_address_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllNameOfAddressUnitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllNameOfAddressUnitResponse) ProtoMessage() {}

func (x *FindAllNameOfAddressUnitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_address_api_address_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllNameOfAddressUnitResponse.ProtoReflect.Descriptor instead.
func (*FindAllNameOfAddressUnitResponse) Descriptor() ([]byte, []int) {
	return file_api_address_api_address_api_proto_rawDescGZIP(), []int{7}
}

func (x *FindAllNameOfAddressUnitResponse) GetUnit() []*AddressUnit {
	if x != nil {
		return x.Unit
	}
	return nil
}

var File_api_address_api_address_api_proto protoreflect.FileDescriptor

var file_api_address_api_address_api_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2d, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x2d, 0x0a, 0x15, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x22, 0x32, 0x0a, 0x16, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x22, 0x8b, 0x01, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x24, 0x0a, 0x0e, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x77, 0x61, 0x72, 0x64, 0x46, 0x75,
	0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x63, 0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x10, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65,
	0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x46, 0x75, 0x6c, 0x6c, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x3e, 0x0a, 0x18, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0x50, 0x0a, 0x19, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x27, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x22, 0x57, 0x0a, 0x1f, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4e,
	0x61, 0x6d, 0x65, 0x4f, 0x66, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x55, 0x6e, 0x69, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x75,
	0x6e, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x22, 0x35, 0x0a,
	0x0b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x22, 0x44, 0x0a, 0x20, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4e,
	0x61, 0x6d, 0x65, 0x4f, 0x66, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x55, 0x6e, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x55, 0x6e, 0x69, 0x74, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x32, 0xe5, 0x02, 0x0a, 0x0e, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x61, 0x0a,
	0x0e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x16, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c,
	0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x12, 0x16, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x12, 0x84, 0x01, 0x0a, 0x18, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65,
	0x4f, 0x66, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x20, 0x2e,
	0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x4f, 0x66, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x4f, 0x66, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x12, 0x1b, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2f, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x2d, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x69, 0x0a, 0x11, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x19, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x45, 0x78, 0x69, 0x73, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45,
	0x78, 0x69, 0x73, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x12, 0x15, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2f, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6e, 0x67, 0x75, 0x79, 0x65, 0x6e, 0x74, 0x72, 0x75, 0x6e, 0x67, 0x68, 0x69, 0x65, 0x75,
	0x31, 0x35, 0x2f, 0x62, 0x65, 0x2d, 0x62, 0x65, 0x65, 0x68, 0x6f, 0x6d, 0x65, 0x2d, 0x70, 0x72,
	0x6a, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_address_api_address_api_proto_rawDescOnce sync.Once
	file_api_address_api_address_api_proto_rawDescData = file_api_address_api_address_api_proto_rawDesc
)

func file_api_address_api_address_api_proto_rawDescGZIP() []byte {
	file_api_address_api_address_api_proto_rawDescOnce.Do(func() {
		file_api_address_api_address_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_address_api_address_api_proto_rawDescData)
	})
	return file_api_address_api_address_api_proto_rawDescData
}

var file_api_address_api_address_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_address_api_address_api_proto_goTypes = []interface{}{
	(*FindAllAddressRequest)(nil),            // 0: FindAllAddressRequest
	(*FindAllAddressResponse)(nil),           // 1: FindAllAddressResponse
	(*Address)(nil),                          // 2: Address
	(*CheckExistAddressRequest)(nil),         // 3: CheckExistAddressRequest
	(*CheckExistAddressResponse)(nil),        // 4: CheckExistAddressResponse
	(*FindAllNameOfAddressUnitRequest)(nil),  // 5: FindAllNameOfAddressUnitRequest
	(*AddressUnit)(nil),                      // 6: AddressUnit
	(*FindAllNameOfAddressUnitResponse)(nil), // 7: FindAllNameOfAddressUnitResponse
}
var file_api_address_api_address_api_proto_depIdxs = []int32{
	2, // 0: CheckExistAddressRequest.address:type_name -> Address
	2, // 1: CheckExistAddressResponse.address:type_name -> Address
	6, // 2: FindAllNameOfAddressUnitRequest.unit:type_name -> AddressUnit
	6, // 3: FindAllNameOfAddressUnitResponse.unit:type_name -> AddressUnit
	0, // 4: AddressService.FindAllAddress:input_type -> FindAllAddressRequest
	5, // 5: AddressService.FindAllNameOfAddressUnit:input_type -> FindAllNameOfAddressUnitRequest
	3, // 6: AddressService.CheckExistAddress:input_type -> CheckExistAddressRequest
	1, // 7: AddressService.FindAllAddress:output_type -> FindAllAddressResponse
	7, // 8: AddressService.FindAllNameOfAddressUnit:output_type -> FindAllNameOfAddressUnitResponse
	4, // 9: AddressService.CheckExistAddress:output_type -> CheckExistAddressResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_address_api_address_api_proto_init() }
func file_api_address_api_address_api_proto_init() {
	if File_api_address_api_address_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_address_api_address_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllAddressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_address_api_address_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllAddressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_address_api_address_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_address_api_address_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckExistAddressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_address_api_address_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckExistAddressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_address_api_address_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllNameOfAddressUnitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_address_api_address_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressUnit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_address_api_address_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllNameOfAddressUnitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_address_api_address_api_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_address_api_address_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_address_api_address_api_proto_goTypes,
		DependencyIndexes: file_api_address_api_address_api_proto_depIdxs,
		MessageInfos:      file_api_address_api_address_api_proto_msgTypes,
	}.Build()
	File_api_address_api_address_api_proto = out.File
	file_api_address_api_address_api_proto_rawDesc = nil
	file_api_address_api_address_api_proto_goTypes = nil
	file_api_address_api_address_api_proto_depIdxs = nil
}
